<?xml version="1.0"?>
<package format="3">
  <name>data_collection</name>
  <version>0.1.0</version>
  <description>Real-robot demonstration collection for Neuro-Flow BC training</description>
  <maintainer email="gowtham.n.mail@gmail.com">Gowtham Natarajan</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>ros_robot_controller_msgs</depend>
  <depend>cv_bridge</depend>

  <buildtool_depend>ament_python</buildtool_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
